import { SymbolCode } from "@/types/weather";
import React from "react";

interface WeatherDescriptionProps {
	symbolCode: SymbolCode | undefined;
}

export const WeatherDescription: React.FC<WeatherDescriptionProps> = ({
	symbolCode,
}) => {
	const descriptions: Record<SymbolCode, string> = {
		clearsky_day: "Sonnig",
		clearsky_night: "Klar",
		clearsky_polartwilight: "Klar",
		cloudy: "Bedeckt",
		fair_day: "Heiter",
		fair_night: "Heiter",
		fair_polartwilight: "Heiter",
		fog: "Nebel",
		heavyrain: "Starkregen",
		heavyrainandthunder: "Gewitter",
		heavyrainshowers_day: "Starkregen",
		heavyrainshowers_night: "Starkregen",
		heavyrainshowers_polartwilight: "Starkregen",
		heavyrainshowersandthunder_day: "Gewitter",
		heavyrainshowersandthunder_night: "Gewitter",
		heavyrainshowersandthunder_polartwilight: "Gewitter",
		heavysleet: "Eisregen",
		heavysleetandthunder: "Eisgewitter",
		heavysleetshowers_day: "Eisregen",
		heavysleetshowers_night: "Eisregen",
		heavysleetshowers_polartwilight: "Eisregen",
		heavysleetshowersandthunder_day: "Eisgewitter",
		heavysleetshowersandthunder_night: "Eisgewitter",
		heavysleetshowersandthunder_polartwilight: "Eisgewitter",
		heavysnow: "Starkschnee",
		heavysnowandthunder: "Schneesturm",
		heavysnowshowers_day: "Starkschnee",
		heavysnowshowers_night: "Starkschnee",
		heavysnowshowers_polartwilight: "Starkschnee",
		heavysnowshowersandthunder_day: "Schneesturm",
		heavysnowshowersandthunder_night: "Schneesturm",
		heavysnowshowersandthunder_polartwilight: "Schneesturm",
		lightrain: "Nieselregen",
		lightrainandthunder: "Gewitter",
		lightrainshowers_day: "Nieselregen",
		lightrainshowers_night: "Nieselregen",
		lightrainshowers_polartwilight: "Nieselregen",
		lightrainshowersandthunder_day: "Gewitter",
		lightrainshowersandthunder_night: "Gewitter",
		lightrainshowersandthunder_polartwilight: "Gewitter",
		lightsleet: "Leichter Eisregen",
		lightsleetandthunder: "Leichtes Eisgewitter",
		lightsleetshowers_day: "Eisregen",
		lightsleetshowers_night: "Eisregen",
		lightsleetshowers_polartwilight: "Eisregen",
		lightsnow: "Leichter Schnee",
		lightsnowandthunder: "Schneesturm",
		lightsnowshowers_day: "Leichter Schnee",
		lightsnowshowers_night: "Leichter Schnee",
		lightsnowshowers_polartwilight: "Leichter Schnee",
		lightssleetshowersandthunder_day: "Eisgewitter",
		lightssleetshowersandthunder_night: "Eisgewitter",
		lightssleetshowersandthunder_polartwilight: "Eisgewitter",
		lightssnowshowersandthunder_day: "Schneesturm",
		lightssnowshowersandthunder_night: "Schneesturm",
		lightssnowshowersandthunder_polartwilight: "Schneesturm",
		partlycloudy_day: "Wolkig",
		partlycloudy_night: "Wolkig",
		partlycloudy_polartwilight: "Wolkig",
		rain: "Regen",
		rainandthunder: "Gewitter",
		rainshowers_day: "Regen",
		rainshowers_night: "Regen",
		rainshowers_polartwilight: "Regen",
		rainshowersandthunder_day: "Gewitter",
		rainshowersandthunder_night: "Gewitter",
		rainshowersandthunder_polartwilight: "Gewitter",
		sleet: "Schneeregen",
		sleetandthunder: "Eisgewitter",
		sleetshowers_day: "Schneeregen",
		sleetshowers_night: "Schneeregen",
		sleetshowers_polartwilight: "Schneeregen",
		sleetshowersandthunder_day: "Eisgewitter",
		sleetshowersandthunder_night: "Eisgewitter",
		sleetshowersandthunder_polartwilight: "Eisgewitter",
		snow: "Schnee",
		snowandthunder: "Schneesturm",
		snowshowers_day: "Schnee",
		snowshowers_night: "Schnee",
		snowshowers_polartwilight: "Schnee",
		snowshowersandthunder_day: "Schneesturm",
		snowshowersandthunder_night: "Schneesturm",
		snowshowersandthunder_polartwilight: "Schneesturm",
	};

	return descriptions[symbolCode as SymbolCode] || "Unbekannt";
};
