import { SymbolCode } from "@/types/weather";
import React from "react";
import { IconBaseProps } from "react-icons/lib";
import {
	WiCloud,
	WiDayCloudy,
	WiDaySunny,
	WiFog,
	WiNightAltCloudy,
	WiNightClear,
	WiRain,
	WiShowers,
	WiSleet,
	WiSnow,
	WiSnowWind,
	WiStormShowers,
	WiThunderstorm,
} from "react-icons/wi";

export default function WeatherIcon({
	symbolCode,
	...props
}: {
	symbolCode: SymbolCode | undefined;
} & IconBaseProps) {
	const iconMap: Record<SymbolCode, React.ReactNode> = {
		clearsky_day: <WiDaySunny {...props} />,
		clearsky_night: <WiNightClear {...props} />,
		clearsky_polartwilight: <WiDaySunny {...props} />,
		cloudy: <WiCloud {...props} />,
		fair_day: <WiDaySunny {...props} />,
		fair_night: <WiNightClear {...props} />,
		fair_polartwilight: <WiDaySunny {...props} />,
		fog: <WiFog {...props} />,
		heavyrain: <WiRain {...props} />,
		heavyrainandthunder: <WiThunderstorm {...props} />,
		heavyrainshowers_day: <WiShowers {...props} />,
		heavyrainshowers_night: <WiShowers {...props} />,
		heavyrainshowers_polartwilight: <WiShowers {...props} />,
		heavyrainshowersandthunder_day: <WiStormShowers {...props} />,
		heavyrainshowersandthunder_night: <WiStormShowers {...props} />,
		heavyrainshowersandthunder_polartwilight: <WiStormShowers {...props} />,
		heavysleet: <WiSleet {...props} />,
		heavysleetandthunder: <WiThunderstorm {...props} />,
		heavysleetshowers_day: <WiSleet {...props} />,
		heavysleetshowers_night: <WiSleet {...props} />,
		heavysleetshowers_polartwilight: <WiSleet {...props} />,
		heavysleetshowersandthunder_day: <WiThunderstorm {...props} />,
		heavysleetshowersandthunder_night: <WiThunderstorm {...props} />,
		heavysleetshowersandthunder_polartwilight: (
			<WiThunderstorm {...props} />
		),
		heavysnow: <WiSnow {...props} />,
		heavysnowandthunder: <WiSnowWind {...props} />,
		heavysnowshowers_day: <WiSnow {...props} />,
		heavysnowshowers_night: <WiSnow {...props} />,
		heavysnowshowers_polartwilight: <WiSnow {...props} />,
		heavysnowshowersandthunder_day: <WiSnowWind {...props} />,
		heavysnowshowersandthunder_night: <WiSnowWind {...props} />,
		heavysnowshowersandthunder_polartwilight: <WiSnowWind {...props} />,
		lightrain: <WiRain {...props} />,
		lightrainandthunder: <WiThunderstorm {...props} />,
		lightrainshowers_day: <WiShowers {...props} />,
		lightrainshowers_night: <WiShowers {...props} />,
		lightrainshowers_polartwilight: <WiShowers {...props} />,
		lightrainshowersandthunder_day: <WiStormShowers {...props} />,
		lightrainshowersandthunder_night: <WiStormShowers {...props} />,
		lightrainshowersandthunder_polartwilight: <WiStormShowers {...props} />,
		lightsleet: <WiSleet {...props} />,
		lightsleetandthunder: <WiThunderstorm {...props} />,
		lightsleetshowers_day: <WiSleet {...props} />,
		lightsleetshowers_night: <WiSleet {...props} />,
		lightsleetshowers_polartwilight: <WiSleet {...props} />,
		lightsnow: <WiSnow {...props} />,
		lightsnowandthunder: <WiSnowWind {...props} />,
		lightsnowshowers_day: <WiSnow {...props} />,
		lightsnowshowers_night: <WiSnow {...props} />,
		lightsnowshowers_polartwilight: <WiSnow {...props} />,
		lightssleetshowersandthunder_day: <WiThunderstorm {...props} />,
		lightssleetshowersandthunder_night: <WiThunderstorm {...props} />,
		lightssleetshowersandthunder_polartwilight: (
			<WiThunderstorm {...props} />
		),
		lightssnowshowersandthunder_day: <WiSnowWind {...props} />,
		lightssnowshowersandthunder_night: <WiSnowWind {...props} />,
		lightssnowshowersandthunder_polartwilight: <WiSnowWind {...props} />,
		partlycloudy_day: <WiDayCloudy {...props} />,
		partlycloudy_night: <WiNightAltCloudy {...props} />,
		partlycloudy_polartwilight: <WiDayCloudy {...props} />,
		rain: <WiRain {...props} />,
		rainandthunder: <WiThunderstorm {...props} />,
		rainshowers_day: <WiShowers {...props} />,
		rainshowers_night: <WiShowers {...props} />,
		rainshowers_polartwilight: <WiShowers {...props} />,
		rainshowersandthunder_day: <WiStormShowers {...props} />,
		rainshowersandthunder_night: <WiStormShowers {...props} />,
		rainshowersandthunder_polartwilight: <WiStormShowers {...props} />,
		sleet: <WiSleet {...props} />,
		sleetandthunder: <WiThunderstorm {...props} />,
		sleetshowers_day: <WiSleet {...props} />,
		sleetshowers_night: <WiSleet {...props} />,
		sleetshowers_polartwilight: <WiSleet {...props} />,
		sleetshowersandthunder_day: <WiThunderstorm {...props} />,
		sleetshowersandthunder_night: <WiThunderstorm {...props} />,
		sleetshowersandthunder_polartwilight: <WiThunderstorm {...props} />,
		snow: <WiSnow {...props} />,
		snowandthunder: <WiSnowWind {...props} />,
		snowshowers_day: <WiSnow {...props} />,
		snowshowers_night: <WiSnow {...props} />,
		snowshowers_polartwilight: <WiSnow {...props} />,
		snowshowersandthunder_day: <WiSnowWind {...props} />,
		snowshowersandthunder_night: <WiSnowWind {...props} />,
		snowshowersandthunder_polartwilight: <WiSnowWind {...props} />,
	};

	return iconMap[symbolCode as SymbolCode] || <WiDaySunny {...props} />;
}
